"""
Phase 16: Multi-City / Multi-Agency Fusion Cloud

This module provides the G3TI Fusion Cloud infrastructure for:
- Multi-tenant architecture (cities, departments, task forces)
- Cross-agency data federation
- Shared investigations and intelligence channels
- Joint operations management
- Federated analytics and heatmaps
- CJIS-compliant cross-domain security
"""

from app.fusion_cloud.multi_tenant import (
    MultiTenantManager,
    Tenant,
    TenantType,
    TenantStatus,
    TenantProfile,
    TenantPolicy,
    DataSource,
    DataSourceType,
    IntegrationConfig,
    IntegrationStatus,
)
from app.fusion_cloud.federation import (
    FederationLayer,
    FederatedData,
    FederatedDataType,
    DataClassification,
    SensitivityLevel,
    JurisdictionTag,
    ClearanceLevel,
    RetentionPolicy,
    FederationSubscription,
    FederationPermission,
)
from app.fusion_cloud.shared_intel import (
    SharedIntelHub,
    IntelChannel,
    ChannelType,
    IntelMessage,
    MessagePriority,
    MessageStatus,
    AgencyACL,
    SubscriptionConfig,
)
from app.fusion_cloud.joint_ops import (
    JointOpsManager,
    JointOperation,
    OperationType,
    OperationStatus,
    OperationRoom,
    OperationRole,
    SharedTimeline,
    TimelineEvent,
    TimelineEventType,
    WhiteboardItemType,
    AgencyParticipation,
    OperationUnit,
    OperationObjective,
)
from app.fusion_cloud.federated_analytics import (
    FederatedAnalyticsEngine,
    RegionalHeatmap,
    HeatmapType,
    CrossCityTrajectory,
    RegionalCluster,
    ClusterType,
    FederatedRiskMap,
    RiskLevel,
)
from app.fusion_cloud.secure_gateway import (
    SecureAccessGateway,
    AccessPolicy,
    AccessDecision,
    AttributeBasedAccess,
    ClearanceFilter,
    TenantEncryption,
    DomainSeparation,
    DataSensitivity,
    AccessRequest,
    AccessResult,
)

__all__ = [
    "MultiTenantManager",
    "Tenant",
    "TenantType",
    "TenantStatus",
    "TenantProfile",
    "TenantPolicy",
    "DataSource",
    "DataSourceType",
    "IntegrationConfig",
    "IntegrationStatus",
    "FederationLayer",
    "FederatedData",
    "FederatedDataType",
    "DataClassification",
    "SensitivityLevel",
    "JurisdictionTag",
    "ClearanceLevel",
    "RetentionPolicy",
    "FederationSubscription",
    "FederationPermission",
    "SharedIntelHub",
    "IntelChannel",
    "ChannelType",
    "IntelMessage",
    "MessagePriority",
    "MessageStatus",
    "AgencyACL",
    "SubscriptionConfig",
    "JointOpsManager",
    "JointOperation",
    "OperationType",
    "OperationStatus",
    "OperationRoom",
    "OperationRole",
    "SharedTimeline",
    "TimelineEvent",
    "TimelineEventType",
    "WhiteboardItemType",
    "AgencyParticipation",
    "OperationUnit",
    "OperationObjective",
    "FederatedAnalyticsEngine",
    "RegionalHeatmap",
    "HeatmapType",
    "CrossCityTrajectory",
    "RegionalCluster",
    "ClusterType",
    "FederatedRiskMap",
    "RiskLevel",
    "SecureAccessGateway",
    "AccessPolicy",
    "AccessDecision",
    "AttributeBasedAccess",
    "ClearanceFilter",
    "TenantEncryption",
    "DomainSeparation",
    "DataSensitivity",
    "AccessRequest",
    "AccessResult",
]
